// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTvwKIgbyfZiu2EXmUkLkJt8uVMfeYYBw',
    appId: '1:341287897612:web:1d1864e49028aed2ca3c29',
    messagingSenderId: '341287897612',
    projectId: 'movie-route-project',
    authDomain: 'movie-route-project.firebaseapp.com',
    storageBucket: 'movie-route-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw0fzmn2ZGJvVO8dTAkFe7DH8OZ4v6iO4',
    appId: '1:341287897612:android:186a2898ebc99d44ca3c29',
    messagingSenderId: '341287897612',
    projectId: 'movie-route-project',
    storageBucket: 'movie-route-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4BvpPTr-N7tACSyHNJKcRuSHn4dtIQqQ',
    appId: '1:341287897612:ios:095ebed9a28984deca3c29',
    messagingSenderId: '341287897612',
    projectId: 'movie-route-project',
    storageBucket: 'movie-route-project.firebasestorage.app',
    androidClientId: '341287897612-7ipl4r5h08lq81nkai03emeibogpdb8b.apps.googleusercontent.com',
    iosClientId: '341287897612-eegksl1ni3k5v8rfekhm7m9ht8veg35g.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies',
  );
}
